# [START cloudbuild]
steps:
# Constroi a imagem Docker
- name: 'gcr.io/cloud-builders/docker'
  id: Docker Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/htmrt-frontend:$SHORT_SHA'
  - '.'

# Envia as imagens para registry e substitui variáveis durante execução
- name: 'gcr.io/cloud-builders/docker'
  id: Push Docker Image
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/htmrt-frontend:$SHORT_SHA'

# Clona o repositório de configuração do ambiente (cluster)
- name: 'gcr.io/cloud-builders/git'
  id: Clone Environment Project
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
      git clone https://github.com/marcusrodmag/htmrt.git && \
      cd htmrt
      git checkout $BRANCH_NAME

# Gera um novo manifesto para definição do cluster usando nova imagem
- name: 'gcr.io/cloud-builders/gcloud'
  id: Generate k8s manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    export ENVNAME=Production| \
    echo "VAR: $$ENVNAME"
    sed "s/GOOGLE_CLOUD_PROJECT/${PROJECT_ID}/g" kubernetes-manifests/htmrt-frontend.yaml.template| \
    sed "s/GOOGLE_EXT_IP/${_CLUSTER_EXTERNAL_IP}/g" kubernetes-manifests/htmrt-frontend.yaml.template| \
    sed "s/COMMIT_SHA/${SHORT_SHA}/g" > htmrt/kubernetes/htmrt-frontend.yaml && \
    cat htmrt/kubernetes/htmrt-frontend.yaml

# Aplica o manifesto gerado
- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy to kubernetes
  args:
  - 'apply'
  - '-f'
  - 'htmrt/kubernetes/htmrt-frontend.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-f'
  - 'CLOUDSDK_CONTAINER_CLUSTER=htmrt-dev'

# Obtem chave ssh privada para autenticação no github
- name: 'gcr.io/cloud-builders/gcloud'
  id: Decript MKS SSH key for github
  args:
  - kms
  - decrypt
  - --ciphertext-file=htmrt/key/id_rsa.enc
  - --plaintext-file=/root/.ssh/id_rsa
  - --location=global
  - --keyring=0001-keyring
  - --key=0001-rtmrt-key
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Commit e PUSH para GIT
- name: 'gcr.io/cloud-builders/git'
  id: Commit do GIT
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    echo "Persist k8s Manifest generated" && \
    ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts && \
    cd htmrt && \
    chmod 400 /root/.ssh/id_rsa && \
    git config --global user.name gitops && \
    git config --global user.email gitops@gmail.com && \
    git remote set-url origin git@github.com:marcusrodmag/htmrt.git && \
    git remote -v && \
    git add . && \
    git commit -m "Manifest from commit $COMMIT_SHA" && \
    git push origin $BRANCH_NAME
  volumes:
  - name: 'ssh'
    path: /root/.ssh

substitutions:
  _CLUSTER_EXTERNAL_IP_PRD: 35.238.105.178
  _CLUSTER_EXTERNAL_IP_DEV: 104.198.104.13
  _POD_ENV_NAME_DEV: DEV 
  _POD_ENV_NAME_PRD: PRD 


# [END cloudbuild]
